cabal: head
jobs:
    include:
      - ghc: 8.6.3
        script:
          - cabal new-update
          - cabal new-build all --only-dependencies -w ghc-8.6.3
      - ghc: head
        script:
          - cabal new-update
          - cabal new-build all --only-dependencies -w ghc-head
      - ghc: head
        script:
          - cabal new-update
          - cabal new-build all --only-dependencies
language: haskell
notifications:
    email: false
sudo: false
