jobs:
    include:
      - cabal: 2.4
        ghc: 8.6.3
        script:
          - cabal new-update
          - cabal new-build all --only-dependencies --project-file=cabal.8.6.project
      - cabal: head
        ghc: head
        script:
          - cabal new-update
          - cabal new-build all --only-dependencies --project-file=cabal.head.project
language: haskell
notifications:
    email: false
sudo: false
